### PR TITLE
Changes updated

### PR DESCRIPTION
**Pull request by sohaibabbasi26**

### CODE REVIEW

**Review by sohaibabbasi26 — COMMENTED** [review]
i have reviewed all the conflicts

**Review by Faria-siddiqi — APPROVED** [review]

**Review by Faria-siddiqi — APPROVED** [review]

**Review by Faria-siddiqi — APPROVED** [review]

**Review by MehdiRazaNaqvi — APPROVED** [review]
reviewed

**Review by Faria-siddiqi — COMMENTED** [review]
Ok done

**Review by Faria-siddiqi — APPROVED** [review]
reviewed

**Review by Ayesha-sadaf — APPROVED** [review]

**Review by muhammadshahab48 — APPROVED** [review]
okay boss done ...

**Pull request merged**
